Repository hakzzang/Burnout, pull requests merged in 2020-08, with the labels that each got.

#3 close #2 Project 구조 잡기
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hbs/burnout/BaseApplication.kt
  app/src/main/java/com/hbs/burnout/core/BaseActivity.kt
  app/src/main/java/com/hbs/burnout/ui/main/MainActivity.kt
  app/src/main/java/com/hbs/burnout/ui/main/MainViewModel.kt
  app/src/main/res/layout/activity_main.xml
  build.gradle
  dependencies.gradle
Labels: API, Gradle, UI

#10 close #4 Main 화면 ui 및 애니메이션 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hbs/burnout/MainActivity.kt
  app/src/main/java/com/hbs/burnout/core/BaseActivity.kt
  app/src/main/java/com/hbs/burnout/ui/main/MainActivity.kt
  app/src/main/java/com/hbs/burnout/ui/main/MissionAdapter.kt
  app/src/main/java/com/hbs/burnout/ui/mission/MissionActivity.kt
  app/src/main/java/com/hbs/burnout/utils/ActivityNavigation.kt
  app/src/main/java/com/hbs/burnout/utils/TransitionManager.kt
  app/src/main/res/drawable/ic_baseline_message_24.xml
  app/src/main/res/drawable/ic_baseline_message_white_24.xml
  app/src/main/res/drawable/ic_drawer_menu_24px.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_mission.xml
  app/src/main/res/layout/item_mission.xml
  app/src/main/res/layout/sample_item_grid_card.xml
  app/src/main/res/menu/main_menu.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
  dependencies.gradle
Labels: Gradle, UI

#11 close #6 채팅 화면 ui 추가
  app/src/main/java/com/hbs/burnout/model/Chatting.kt
  app/src/main/java/com/hbs/burnout/ui/mission/ChattingAdapter.kt
  app/src/main/java/com/hbs/burnout/ui/mission/MissionActivity.kt
  app/src/main/java/com/hbs/burnout/ui/mission/MissionViewModel.kt
  app/src/main/res/drawable/gamjatwigim.png
  app/src/main/res/drawable/ic_baseline_add_24.xml
  app/src/main/res/drawable/shrimp.png
  app/src/main/res/layout/activity_mission.xml
  app/src/main/res/layout/item_my_chatting.xml
  app/src/main/res/layout/item_your_chatting.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: UI

#15 closed #12 다크테마 추가하기
  app/src/main/java/com/hbs/burnout/core/BaseActivity.kt
  app/src/main/java/com/hbs/burnout/utils/TransitionManager.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_mission.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values-night/styles.xml
  app/src/main/res/values-notnight/styles.xml
Labels: UI

#17 close #16 메인화면 리스트 구조 변경
  app/src/main/java/com/hbs/burnout/core/BaseActivity.kt
  app/src/main/java/com/hbs/burnout/ui/main/MainActivity.kt
  app/src/main/java/com/hbs/burnout/ui/mission/MissionActivity.kt
  app/src/main/java/com/hbs/burnout/utils/TransitionManager.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_mission.xml
Labels: UI

#21 closed #13 공유화면 UI 작업
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hbs/burnout/model/ShareResult.kt
  app/src/main/java/com/hbs/burnout/ui/main/MainActivity.kt
  app/src/main/java/com/hbs/burnout/ui/share/ProgressAdapter.kt
  app/src/main/java/com/hbs/burnout/ui/share/ShareActivity.kt
  app/src/main/java/com/hbs/burnout/ui/share/ShareViewModel.kt
  app/src/main/res/drawable/bg_circle.xml
  app/src/main/res/drawable/bg_img_rounded.xml
  app/src/main/res/drawable/bg_progress_share.xml
  app/src/main/res/drawable/ic_btn_back.xml
  app/src/main/res/drawable/ic_btn_next.xml
  app/src/main/res/drawable/ic_btn_share.xml
  app/src/main/res/layout/activity_share.xml
  app/src/main/res/layout/item_share_progress.xml
  app/src/main/res/values/colors.xml
Labels: UI

#23 스크립트 매니저 추가하기
  app/src/main/java/com/hbs/burnout/core/BaseActivity.kt
  app/src/main/java/com/hbs/burnout/core/Event.kt
  app/src/main/java/com/hbs/burnout/model/Chatting.kt
  app/src/main/java/com/hbs/burnout/ui/main/MainActivity.kt
  app/src/main/java/com/hbs/burnout/ui/main/MainViewModel.kt
  app/src/main/java/com/hbs/burnout/ui/mission/ChattingAdapter.kt
  app/src/main/java/com/hbs/burnout/ui/mission/MissionActivity.kt
  app/src/main/java/com/hbs/burnout/ui/mission/MissionViewModel.kt
  app/src/main/java/com/hbs/burnout/utils/ScriptManager.kt
  app/src/main/java/com/hbs/burnout/utils/TransitionManager.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_mission.xml
  app/src/main/res/layout/item_my_chatting.xml
  app/src/main/res/layout/item_your_chatting.xml
Labels: UI, feature

#42 close #41 Stage UI 및 로직 추가하기
  app/src/main/java/com/hbs/burnout/domain/local/usecase/MainUseCase.kt
  app/src/main/java/com/hbs/burnout/model/Stage.kt
  app/src/main/java/com/hbs/burnout/ui/main/MainActivity.kt
  app/src/main/java/com/hbs/burnout/ui/main/MainViewModel.kt
  app/src/main/java/com/hbs/burnout/ui/main/MissionAdapter.kt
  app/src/main/java/com/hbs/burnout/ui/main/adapter/MissionAdapter.kt
  app/src/main/java/com/hbs/burnout/ui/main/adapter/MissionHelper.kt
  app/src/main/res/badge/apple.png
  app/src/main/res/badge/banana.png
  app/src/main/res/badge/broccoli.png
  app/src/main/res/badge/mango.png
  app/src/main/res/badge/orange.png
  app/src/main/res/badge/paprika.png
  app/src/main/res/badge/strawberry.png
  app/src/main/res/badge/tangerine.png
  app/src/main/res/badge/tomato.png
  app/src/main/res/badge/watermelon.png
  app/src/main/res/drawable/apple.webp
  app/src/main/res/drawable/banana.webp
  app/src/main/res/drawable/broccoli.webp
  app/src/main/res/drawable/ic_lock.xml
  app/src/main/res/drawable/mango.webp
  app/src/main/res/drawable/orange.webp
  app/src/main/res/drawable/paprika.webp
  app/src/main/res/drawable/strawberry.webp
  app/src/main/res/drawable/tangerine.webp
  app/src/main/res/drawable/tomato.webp
  app/src/main/res/drawable/watermelon.webp
  app/src/main/res/layout/item_mission.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
Labels: UI, feature

#44 close #43 뱃지관련 중복된 이미지 경로로 인한 버그 수정 #43
  app/src/main/res/badge/apple.png
  app/src/main/res/badge/banana.png
  app/src/main/res/badge/broccoli.png
  app/src/main/res/badge/mango.png
  app/src/main/res/badge/orange.png
  app/src/main/res/badge/paprika.png
  app/src/main/res/badge/strawberry.png
  app/src/main/res/badge/tangerine.png
  app/src/main/res/badge/tomato.png
  app/src/main/res/badge/watermelon.png
Labels: bug

#46 close #45 SelectionView 백그라운드 색깔 제거하기
  app/src/main/java/com/hbs/burnout/ui/chat/ChattingFragment.kt
  app/src/main/java/com/hbs/burnout/ui/ext/dialog/AnswerDialog.kt
  app/src/main/res/layout/dialog_selection.xml
  app/src/main/res/layout/view_selection.xml
  app/src/main/res/values/dimens.xml
Labels: UI

#49 뱃지함 만들기
  app/src/main/java/com/hbs/burnout/domain/local/usecase/MainUseCase.kt
  app/src/main/java/com/hbs/burnout/model/Stage.kt
  app/src/main/java/com/hbs/burnout/ui/ext/view/ExtView.kt
  app/src/main/java/com/hbs/burnout/ui/main/MainActivity.kt
  app/src/main/java/com/hbs/burnout/ui/main/MainViewModel.kt
  app/src/main/java/com/hbs/burnout/ui/main/adapter/BadgeAdapter.kt
  app/src/main/java/com/hbs/burnout/ui/main/adapter/MissionAdapter.kt
  app/src/main/java/com/hbs/burnout/utils/script/MissionHelper.kt
  app/src/main/res/drawable/apple_dark.webp
  app/src/main/res/drawable/banana_dark.webp
  app/src/main/res/drawable/broccoli_dark.webp
  app/src/main/res/drawable/mango_dark.webp
  app/src/main/res/drawable/orange_dark.webp
  app/src/main/res/drawable/paprika_dark.webp
  app/src/main/res/drawable/strawberry_dark.webp
  app/src/main/res/drawable/tangerine_dark.webp
  app/src/main/res/drawable/tomato_dark.webp
  app/src/main/res/drawable/watermelon_dark.webp
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/item_badge.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values-notnight/styles.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: UI, feature

#51 close #50 가로모드시에 정상적으로 동작하지 않는 로직 수정
  app/src/main/java/com/hbs/burnout/domain/local/usecase/ChattingUseCase.kt
  app/src/main/java/com/hbs/burnout/ui/chat/ChattingFragment.kt
  app/src/main/java/com/hbs/burnout/ui/chat/ChattingViewModel.kt
  app/src/main/java/com/hbs/burnout/ui/main/MainActivity.kt
  app/src/main/java/com/hbs/burnout/ui/main/MainViewModel.kt
  app/src/main/java/com/hbs/burnout/utils/script/ScriptManager.kt
Labels: bug

#52 close #48 스플레쉬 화면 만들기
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hbs/burnout/ui/main/MainActivity.kt
  app/src/main/res/drawable/splash_background.xml
  app/src/main/res/drawable/splash_burnout_icon.png
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values-night/styles.xml
  app/src/main/res/values-notnight/styles.xml
  app/src/main/res/values/colors.xml
Labels: UI

#57 Feature/issue 39
  app/src/main/java/com/hbs/burnout/model/ShareResult.kt
  app/src/main/java/com/hbs/burnout/ui/save/SaveDialog.kt
  app/src/main/java/com/hbs/burnout/ui/share/ShareActivity.kt
  app/src/main/java/com/hbs/burnout/utils/FileUtils.kt
  app/src/main/res/layout/dialog_save.xml
Labels: UI, feature

#64 close #54 채팅에서 사용되어지는 카메라 로직 연결하기
  app/src/main/java/com/hbs/burnout/ui/camera/CameraMissionActivity.kt
  app/src/main/java/com/hbs/burnout/ui/camera/fragments/CameraFragment.kt
  app/src/main/java/com/hbs/burnout/ui/camera/fragments/PermissionsFragment.kt
  app/src/main/java/com/hbs/burnout/ui/camera/fragments/PreviewResultFragment.kt
  app/src/main/java/com/hbs/burnout/ui/chat/ChattingAdapter.kt
  app/src/main/java/com/hbs/burnout/ui/chat/ChattingFragment.kt
  app/src/main/java/com/hbs/burnout/ui/ext/view/ExtObject.kt
  app/src/main/java/com/hbs/burnout/ui/share/ShareActivity.kt
  app/src/main/java/com/hbs/burnout/ui/share/ShareViewModel.kt
  app/src/main/java/com/hbs/burnout/utils/ActivityNavigation.kt
  app/src/main/java/com/hbs/burnout/utils/FileUtils.kt
  app/src/main/res/drawable/ic_btn_back.xml
  app/src/main/res/drawable/ic_complete.xml
  app/src/main/res/layout/activity_share.xml
  app/src/main/res/layout/item_my_chatting.xml
  app/src/main/res/layout/item_share_progress.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values-night/styles.xml
  app/src/main/res/values-notnight/styles.xml
  app/src/main/res/values/colors.xml
Labels: UI, feature

#67 close #65 머지하는 과정에서 발생하는 오류 수정
  app/src/main/java/com/hbs/burnout/utils/FileUtils.kt
  app/src/main/res/layout/item_my_chatting.xml
  app/src/main/res/values/dimens.xml
Labels: bug

#68 close #63 FloattingButton 누를 시에 진행하는 미션 연결하기
  app/src/main/java/com/hbs/burnout/ui/main/MainActivity.kt
Labels: UI

#69 close #66 가로모드로 돌아갈 때 버그 수정하기
  app/src/main/java/com/hbs/burnout/ui/chat/ChattingAdapter.kt
  app/src/main/java/com/hbs/burnout/ui/chat/ChattingFragment.kt
  app/src/main/java/com/hbs/burnout/ui/chat/ChattingViewModel.kt
  app/src/main/java/com/hbs/burnout/ui/ext/dialog/AnswerDialog.kt
  app/src/main/java/com/hbs/burnout/utils/script/ScriptStorage.kt
  app/src/main/res/layout/item_last_chatting.xml
Labels: bug

#70 closed #39 공유화면 이미지 다운로드 기능 개발
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hbs/burnout/ui/save/SaveDialog.kt
  app/src/main/java/com/hbs/burnout/utils/FileUtils.kt
  app/src/main/res/layout/dialog_save.xml
Labels: UI, feature

#78 close #58 숏컷 추가하기
  app/src/main/java/com/hbs/burnout/ui/chat/ChattingActivity.kt
  app/src/main/java/com/hbs/burnout/ui/main/MainActivity.kt
  app/src/main/java/com/hbs/burnout/utils/NotificationHelper.kt
Labels: feature

#81 close #80 채팅과 카메라 로직 연결하기
  app/src/main/assets/congratulate.json
  app/src/main/java/com/hbs/burnout/tfml/TFModelWorker.kt
  app/src/main/java/com/hbs/burnout/tfml/classifier/ImageClassifier.kt
  app/src/main/java/com/hbs/burnout/ui/chat/ChattingFragment.kt
  app/src/main/java/com/hbs/burnout/ui/chat/ChattingViewModel.kt
  app/src/main/java/com/hbs/burnout/ui/drawable/DrawImageActivity.kt
  app/src/main/java/com/hbs/burnout/ui/share/ShareActivity.kt
  app/src/main/java/com/hbs/burnout/utils/script/ScriptManager.kt
  app/src/main/java/com/hbs/burnout/utils/script/ScriptStorage.kt
  app/src/main/res/layout/fragment_completed_stage.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: bug, feature

#83 closed #71 공유 화면 Fragment 구조로 변경
  app/src/main/assets/share_normal_0.json
  app/src/main/assets/share_normal_1.json
  app/src/main/assets/share_normal_2.json
  app/src/main/java/com/hbs/burnout/ui/save/SaveDialog.kt
  app/src/main/java/com/hbs/burnout/ui/share/ShareActivity.kt
  app/src/main/java/com/hbs/burnout/ui/share/ShareCameraFragment.kt
  app/src/main/java/com/hbs/burnout/ui/share/ShareNormalFragment.kt
  app/src/main/java/com/hbs/burnout/ui/share/SnsDialog.kt
  app/src/main/java/com/hbs/burnout/utils/FileUtils.kt
  app/src/main/res/drawable/ic_btn_back.xml
  app/src/main/res/layout/activity_share.xml
  app/src/main/res/layout/dialog_save.xml
  app/src/main/res/layout/fragment_share_camera.xml
  app/src/main/res/layout/fragment_share_normal.xml
Labels: UI

#86 close #82 채팅 버그 개선하기
  app/src/main/java/com/hbs/burnout/domain/local/usecase/ChattingUseCase.kt
  app/src/main/java/com/hbs/burnout/ui/chat/ChattingAdapter.kt
  app/src/main/java/com/hbs/burnout/ui/chat/ChattingFragment.kt
  app/src/main/java/com/hbs/burnout/ui/chat/ChattingViewModel.kt
  app/src/main/java/com/hbs/burnout/ui/ext/dialog/AnswerDialog.kt
  app/src/main/java/com/hbs/burnout/ui/ext/dialog/DrawingImageDialog.kt
  app/src/main/java/com/hbs/burnout/ui/ext/dialog/TakePictureDialog.kt
  app/src/main/java/com/hbs/burnout/ui/ext/view/ExtView.kt
  app/src/main/java/com/hbs/burnout/ui/main/MainActivity.kt
  app/src/main/java/com/hbs/burnout/ui/main/adapter/BadgeAdapter.kt
  app/src/main/java/com/hbs/burnout/ui/main/adapter/MissionAdapter.kt
  app/src/main/java/com/hbs/burnout/utils/script/ScriptManager.kt
  app/src/main/res/drawable-anydpi/ic_baseline_drawing_brush.xml
Labels: bug

#87 Feature/issue 40
  app/src/main/java/com/hbs/burnout/di/RepositoryModule.kt
  app/src/main/java/com/hbs/burnout/di/UseCaseModule.kt
  app/src/main/java/com/hbs/burnout/domain/local/repository/ShareRepository.kt
  app/src/main/java/com/hbs/burnout/domain/local/usecase/ShareUseCase.kt
  app/src/main/java/com/hbs/burnout/model/ShareResult.kt
  app/src/main/java/com/hbs/burnout/model/dao/Converters.kt
  app/src/main/java/com/hbs/burnout/model/dao/script/StageDataBase.kt
  app/src/main/java/com/hbs/burnout/model/dao/share/ShareDao.kt
  app/src/main/java/com/hbs/burnout/ui/main/MainActivity.kt
  app/src/main/java/com/hbs/burnout/ui/save/SaveDialog.kt
  app/src/main/java/com/hbs/burnout/ui/share/ShareActivity.kt
  app/src/main/java/com/hbs/burnout/ui/share/ShareCameraFragment.kt
  app/src/main/java/com/hbs/burnout/ui/share/ShareViewModel.kt
  app/src/main/java/com/hbs/burnout/ui/share/SnsDialog.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/item_mission.xml
  app/src/main/res/values-notnight-v23/styles.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: UI

#89 close #55 CompletedStageFragment에 Share 결과 보여주기
  app/src/main/java/com/hbs/burnout/di/UseCaseModule.kt
  app/src/main/java/com/hbs/burnout/domain/local/usecase/ShareUseCase.kt
  app/src/main/java/com/hbs/burnout/ui/chat/CompletedStageFragment.kt
  app/src/main/java/com/hbs/burnout/ui/share/ShareActivity.kt
  app/src/main/java/com/hbs/burnout/ui/share/ShareCameraFragment.kt
  app/src/main/java/com/hbs/burnout/ui/share/ShareViewModel.kt
  app/src/main/res/layout/fragment_completed_stage.xml
  app/src/main/res/layout/fragment_share_camera.xml
  app/src/main/res/values/strings.xml
Labels: UI, feature

#90 close #88 게임 엔딩 화면 만들기
  app/src/main/assets/gameover.json
  app/src/main/java/com/hbs/burnout/ui/chat/ChattingActivity.kt
  app/src/main/java/com/hbs/burnout/ui/chat/ChattingFragment.kt
  app/src/main/java/com/hbs/burnout/ui/ext/dialog/EndingDialog.kt
  app/src/main/java/com/hbs/burnout/ui/ext/view/BottomAppBarCutCornersTopEdge.kt
  app/src/main/java/com/hbs/burnout/ui/ext/view/ExtView.kt
  app/src/main/java/com/hbs/burnout/ui/main/MainActivity.kt
  app/src/main/java/com/hbs/burnout/utils/TransitionManager.kt
  app/src/main/java/com/hbs/burnout/utils/script/MissionHelper.kt
  app/src/main/java/com/hbs/burnout/utils/script/ScriptManager.kt
  app/src/main/res/drawable/ic_moon.xml
  app/src/main/res/drawable/ic_moon_color.xml
  app/src/main/res/layout/activity_chatting.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/dialog_game_ending.xml
  app/src/main/res/layout/item_mission.xml
  app/src/main/res/menu/main_menu.xml
  app/src/main/res/values-night/styles.xml
  app/src/main/res/values-notnight/styles.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: UI, bug, feature

#97 close #96 각종 버그 개선
  app/src/main/java/com/hbs/burnout/model/Script.kt
  app/src/main/java/com/hbs/burnout/ui/chat/ChattingActivity.kt
  app/src/main/java/com/hbs/burnout/ui/chat/ChattingAdapter.kt
  app/src/main/java/com/hbs/burnout/ui/chat/ChattingFragment.kt
  app/src/main/java/com/hbs/burnout/ui/chat/ChattingViewModel.kt
  app/src/main/java/com/hbs/burnout/ui/chat/CompletedStageFragment.kt
  app/src/main/java/com/hbs/burnout/ui/drawable/DrawImageActivity.kt
  app/src/main/java/com/hbs/burnout/ui/ext/dialog/TakePictureDialog.kt
  app/src/main/java/com/hbs/burnout/ui/main/MainActivity.kt
  app/src/main/java/com/hbs/burnout/ui/main/adapter/MissionAdapter.kt
  app/src/main/java/com/hbs/burnout/utils/FileUtils.kt
  app/src/main/java/com/hbs/burnout/utils/NotificationHelper.kt
  app/src/main/java/com/hbs/burnout/utils/script/ScriptManager.kt
  app/src/main/java/com/hbs/burnout/utils/script/ScriptStorage.kt
  app/src/main/res/layout/item_mission.xml
Labels: bug, feature

#99 close #98 메인화면 리스트 속도 개선
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hbs/burnout/model/Stage.kt
  app/src/main/java/com/hbs/burnout/ui/chat/ChattingAdapter.kt
  app/src/main/java/com/hbs/burnout/ui/main/MainActivity.kt
  app/src/main/java/com/hbs/burnout/ui/main/adapter/MissionAdapter.kt
  app/src/main/java/com/hbs/burnout/ui/share/ShareActivity.kt
  app/src/main/java/com/hbs/burnout/utils/FileUtils.kt
  app/src/main/res/layout/item_mission.xml
  app/src/main/res/layout/item_my_chatting.xml
  app/src/main/res/layout/item_your_chatting.xml
  app/src/main/res/values/dimens.xml
Labels: UI, feature

#100 closed #95 공유화면 권한 요청 추가
  app/src/main/java/com/hbs/burnout/ui/save/SaveDialog.kt
  app/src/main/java/com/hbs/burnout/ui/share/SnsDialog.kt
  app/src/main/java/com/hbs/burnout/utils/FileUtils.kt
  app/src/main/java/com/hbs/burnout/utils/IntentUtils.kt
  app/src/main/java/com/hbs/burnout/utils/script/ScriptManager.kt
  app/src/main/res/values/strings.xml
Labels: feature

#103 closed #101 UI 수정
  app/src/main/assets/share_normal_0.json
  app/src/main/assets/share_normal_1.json
  app/src/main/assets/share_normal_2.json
  app/src/main/java/com/hbs/burnout/ui/drawable/DrawImageActivity.kt
  app/src/main/res/drawable-hdpi/ic_baseline_drawing_brush.png
  app/src/main/res/drawable-mdpi/ic_baseline_drawing_brush.png
  app/src/main/res/drawable-xhdpi/ic_baseline_drawing_brush.png
  app/src/main/res/drawable-xxhdpi/ic_baseline_drawing_brush.png
  app/src/main/res/drawable/ic_baseline_drawing_brush.xml
  app/src/main/res/drawable/ic_baseline_photo_camera_24.xml
  app/src/main/res/drawable/ic_btn_back.xml
  app/src/main/res/drawable/ic_btn_chat.xml
  app/src/main/res/drawable/ic_btn_eraser.xml
  app/src/main/res/drawable/ic_btn_refresh.xml
  app/src/main/res/drawable/ic_btn_send.xml
  app/src/main/res/drawable/ic_checkbox_on.xml
  app/src/main/res/drawable/ic_complete.xml
  app/src/main/res/layout/activity_draw.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_share.xml
  app/src/main/res/layout/dialog_drawing_image.xml
  app/src/main/res/layout/dialog_take_picture.xml
  app/src/main/res/layout/fragment_completed_stage.xml
  app/src/main/res/layout/fragment_preview.xml
  app/src/main/res/layout/fragment_share_camera.xml
  app/src/main/res/layout/item_badge.xml
  app/src/main/res/layout/item_share_progress.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: UI
